name: Consolidate JSON Files

on:
  push:
    paths:
      - "snippets/**"

permissions:
  contents: write

jobs:
  consolidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install

      - name: Consolidate Snippets into JSON files
        run: |
          node utils/consolidateSnippets.js  # Run the script located in the utils/ folder
      
      - name: Consolidate JSON files into merged file
        run: |
          node utils/consolidate.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/data/*
          git add public/consolidated/all_snippets.json
          git commit -m "Update consolidated snippets"
          git push
